### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by abbbe** [bave8672/angular-firebase-starter#3]
I encounter multiple javascript error when trying to use the boilerplate.

On attempt to sign-up with Google:

![image](https://user-images.githubusercontent.com/1535574/36605239-78f35ee0-18c0-11e8-95ba-f4150686126c.png)

Behind the scene the sign-up happens, but the popup window stucks. I can manually switch to profile page and kind of use the app, but similar errors pour in on the console.

On attempt to click "send verification email" button:
![image](https://user-images.githubusercontent.com/1535574/36605864-493d5762-18c2-11e8-9170-8e5a668ccbdd.png)

In general the app does not work for me, which is real pity, it looks like a great boilerplate.

**Comment by bave8672** [comment]
Hi @abbbe ,

Thanks for using the boilerplate - I'm sorry you had this experience.

I have recreated your issues; It looks like I merged a feature into to the master branch prematurely - my apologies.

I'm hoping that the most recent commit to master (https://github.com/bave8672/angular-firebase-starter/pull/4) should fix these issues.

Cheers
